[YUNIKORN-2982] Send event when preemption occurs
apache/yunikorn-core pull request #1000
Opened 2024-11-25 11:53 UTC by rhh777

### What is this PR for?
When a preemption occurs, send an event to be displayed in the victim's event list.

### What type of PR is it?
* [x] - Improvement

### What is the Jira issue?
[YUNIKORN-2982](https://issues.apache.org/jira/browse/YUNIKORN-2982)

### How should this be tested?
Trigger preemption

### Screenshots
<img width="2143" alt="image" src="https://github.com/user-attachments/assets/e039f60f-4274-4387-a753-77d9138a15e5">

### Questions:
* [x] - At present, the default interval for event sending is 2 seconds. When sending a preemptive event, the task may have already been removed, triggering an exception that the corresponding task cannot be found, resulting in the failure of event sending.
Narrowing the time interval can be a temporary solution, but I haven't thought of a more suitable solution at the moment.
<img width="2526" alt="image" src="https://github.com/user-attachments/assets/0c344385-e80c-4f8d-9864-57389e47c512">

2024-11-25 14:10 UTC, pbacsko requested changes
See comments.

2024-11-25 14:10 UTC, pbacsko commented on pkg/scheduler/objects/events/application_events.go
> +	event := events.CreateAppEventRecord(appID, message, allocKey, si.EventRecord_REMOVE, si.EventRecord_ALLOC_PREEMPT, allocated)
This must be a `REQUEST` type. That will result in a real K8s event being sent to the target pod.

The removal of the allocation will be a natural consequence of that, which will flow through the scheduler, so an app-specific event is not needed here.

2024-11-25 14:22 UTC, pbacsko commented on pkg/scheduler/objects/preemption.go
> +			message := fmt.Sprintf("Preempted by %v from application %v in %v", p.ask.GetTag("kubernetes.io/meta/podName"), p.ask.applicationID, p.application.queuePath)
I looked at `preemption_test.go`, the simplest test case is `TestTryPreemption`. You can add the extra code there to verify the event.

2024-11-29 08:52 UTC, rhh777 commented
> See comments.

Event has been switched to Request, please continue reviewing.

2024-12-02 06:17 UTC, pbacsko commented on pkg/scheduler/objects/preemption.go
> +			// send event
very nit: unnecessary comment

2024-12-02 06:20 UTC, pbacsko commented
Overall looks good, added @wilfred-s to to have his opinion too.

2024-12-02 08:17 UTC, rhh777 commented on pkg/scheduler/objects/preemption.go
> +			// send event
Updated.

2024-12-02 13:27 UTC, pbacsko approved these changes
LGTM

2024-12-03 06:34 UTC, wilfred-s commented
> This must be a type of REQUEST. That will result in a real K8s event being sent to the target pod.
>
> The removal of the allocation will be a natural consequence of that, which will flow through the scheduler, so an app-specific event is not needed here.

I can see that an application specific event is already generated as part of `removeAllocationInternal()` that handles the overall tracking nicely.
This change adds the missing piece by generating an event on the pod. Based on that I think we're good .

2024-12-03 06:34 UTC, wilfred-s approved these changes
LGTM +1

2024-12-03 10:03 UTC, closed without merging