[YUNIKORN-1326] Develop tracker module.
apache/yunikorn-core pull request #439
Opened 2022-09-23 07:57 UTC by manirajv06

### What is this PR for?
Initial implementation of the tracker module.

### What type of PR is it?
* [ ] - Feature

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1326

### How should this be tested?

### Screenshots (if appropriate)

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

2022-09-23 11:58 UTC, pbacsko commented on pkg/scheduler/ugm/manager.go
> +	sync.RWMutex
You only use `Lock()`, but not `RLock()`, so it's simpler to just use `Mutex`.

2022-09-23 12:00 UTC, pbacsko commented on pkg/scheduler/ugm/manager.go
> +	groups map[string]*GroupTracker
Since this is a mapping, I'd be happier with names like `userTrackers` and `groupTrackers`.

2022-09-23 12:03 UTC, pbacsko commented on pkg/scheduler/ugm/manager.go
> +func (m *Manager) checkAppGroup(applicationID string, user *security.UserGroup) {
To me, it looks like this method makes sure that each group in the manager will have a `GroupTracker`. How about calling it `ensureGroupTrackerForApp()` or something similar?

2022-09-23 12:04 UTC, pbacsko commented on pkg/scheduler/ugm/manager.go
> +func (m *Manager) cleaner() {
Seems to be unused, will there be a code in the future which calls this?

2022-09-23 12:05 UTC, pbacsko commented on pkg/scheduler/ugm/group_tracker.go
> +	queue        *QueueTracker
Nit: `queueTracker` seems to be a better name

2022-09-23 12:08 UTC, pbacsko commented on pkg/scheduler/ugm/group_tracker.go
> +	}
In this code, we only do `gt.Lock()`, if `removeApp` is true. This is not the case with the increase pair, where we call `gt.queue.increaseTrackedResource()` within a lock. Could this be an issue? At least for consistency reasons, I think the behavior should be the same.

2022-09-23 12:10 UTC, pbacsko commented on pkg/scheduler/ugm/manager.go
> +		log.Logger().Info("user tracker must be available in users map",
Not `Logger().Error()`?

2022-09-23 12:11 UTC, pbacsko commented on pkg/scheduler/ugm/manager.go
> +		log.Logger().Info("group tracker must be available in groups map",
Not Logger().Error()?

2022-09-23 12:11 UTC, pbacsko commented on pkg/scheduler/ugm/queue_tracker.go
> +	childQueues         map[string]*QueueTracker
`childQueueTrackers` ?

2022-09-23 12:12 UTC, pbacsko commented on pkg/scheduler/ugm/user_tracker.go
> +	queue    *QueueTracker
`queueTracker` ?

2022-09-30 05:30 UTC, wilfred-s requested changes
The objects and implemented functions do not line up with the design that was made. Moving away from the designed interface needs discussion before we do this.
The changes also mean that the behaviour as described in the design is not implemented.

2022-10-12 09:46 UTC, manirajv06 commented
@wilfred-s and myself reviewed the changes together in a call. Made changes based on the comments.

2022-10-13 04:39 UTC, wilfred-s requested changes
We need to make sure that the coverage for the new code is above 80% at least.

2022-10-13 04:39 UTC, wilfred-s commented on pkg/scheduler/ugm/group_tracker.go
> +		if active {
active is always true so this check is redundant.

2022-10-13 04:39 UTC, wilfred-s commented on pkg/scheduler/ugm/group_tracker.go
> +	resources[usage.QueueName] = usage.ResourceUsage
this breaks when you have two queue with the same name at different levels or under different parents

2022-10-13 04:39 UTC, wilfred-s commented on pkg/scheduler/ugm/manager.go
> +func NewManager() *Manager {
I can call this and re-init the manager which can cause issues. This needs to be shielded by the onceDo()

2022-10-13 04:39 UTC, wilfred-s commented on pkg/scheduler/ugm/user_tracker.go
> +func NewUserTracker(user security.UserGroup) *UserTracker {
should not export this

2022-10-13 04:39 UTC, wilfred-s commented on pkg/scheduler/ugm/queue_tracker.go
> +func NewQueueTracker() *QueueTracker {
should not export this

2022-10-13 04:39 UTC, wilfred-s commented on pkg/scheduler/ugm/group_tracker.go
> +func NewGroupTracker(group string) *GroupTracker {
should not export this

2022-11-04 03:47 UTC, wilfred-s approved these changes
LGTM, change looks good
we'll get he base in and add further tests etc in follow up changes.

2022-11-04 03:49 UTC, closed without merging