[YUNIKORN-1430] change go version check in Makefile
apache/yunikorn-core pull request #457
Opened 2022-11-28 08:38 UTC by wusamzong

### What is this PR for?
Point `MOD_VERSION` to `.go_version`, which will cause the make to fail if go is too old
I am going to update to all repos
[yunikorn-core #457](https://github.com/apache/yunikorn-core/pull/457)
[yunikorn-k8shim #491](https://github.com/apache/yunikorn-k8shim/pull/491)
[yunikorn-scheduler-interface #78](https://github.com/apache/yunikorn-scheduler-interface/pull/78)

### What type of PR is it?
* [x] - Task

### What is the Jira issue?
https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-1430

### How should this be tested?
`make`
### Screenshots (if appropriate)
Here is the result I use go1.16
![image](https://user-images.githubusercontent.com/48400525/204229798-55328a95-f493-4213-bedd-8dcdd7d64315.png)

Here is the result I use go1.18
![image](https://user-images.githubusercontent.com/48400525/204229831-ffc8842b-d674-49ae-9599-4e0486824463.png)

2022-11-29 21:04 UTC, craigcondit requested changes
Need to move the go setup task prior to the license check task.

2022-11-30 06:48 UTC, wusamzong commented
> Need to move the go setup task prior to the license check task.

I’m not sure I understand what you mean.
If it should be changed to the following?
```
.PHONY: run
run: license-check build
	@echo "running scheduler locally"
	...
.PHONY: run_plugin
run_plugin: license-check build_plugin
	@echo "running scheduler plugin locally"
	...
```
Put the `license-check` phase before the `build` phase?

2022-11-30 08:57 UTC, wusamzong commented
> Need to move the go setup task prior to the license check task.

Do you mean that if an error occurs during the `go build` phase, `Build should be run with at least go $(MOD_VERSION) or later, found $(GO_VERSION)` will be displayed?

2022-11-30 13:06 UTC, craigcondit commented
> Do you mean that if an error occurs during the `go build` phase, `Build should be run with at least go $(MOD_VERSION) or later, found $(GO_VERSION)` will be displayed?

No, the build fails because the license check GitHub action comes before the step which installs the correct version of go. You need to update the GitHub workflow file to reverse this order.

2022-12-01 03:49 UTC, wilfred-s approved these changes
LGTM

2022-12-01 03:58 UTC, closed without merging