[YUNIKORN-1610] Enforcement changes for User Based Quota
apache/yunikorn-core pull request #563
Opened 2023-06-09 13:57 UTC by manirajv06

### What is this PR for?
Enforcement checks 

### What type of PR is it
* [ ] - Feature

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1610

### How should this be tested?

### Screenshots (if appropriate)

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

2023-06-13 13:37 UTC, pbacsko commented on pkg/common/configs/config_test.go
> +                    maxresources: ` + leafQueueMaxResource + `
Placeholders

2023-06-13 13:38 UTC, pbacsko commented on pkg/common/configs/config_test.go
> +                    maxresources: ` + userMaxResource + `
Placeholders

2023-06-13 13:38 UTC, pbacsko commented on pkg/common/configs/config_test.go
> +                    maxresources: ` + leafQueueMaxResource + `
Placeholders

2023-06-13 13:49 UTC, pbacsko commented on pkg/common/configs/configvalidator.go
> +				groups[group] = uint64(math.Min(float64(curM), float64(groups[group])))
`Min()` as Wilfred asked.

2023-06-13 13:53 UTC, pbacsko commented on pkg/scheduler/partition_test.go
> +	internalAssertUserGroupResource(t, getTestUserGroup(), resources.NewResourceFromMap(map[string]resources.Quantity{"vcore": 8000}), getExpectedQueuesLimitsForPreemptionWithRequiredNode())
Will you rebase this based on #543? You already made some changes which are similar. Is this related? (You changed `partition_test.go` in #543).

2023-06-13 14:15 UTC, pbacsko commented on pkg/scheduler/ugm/queue_tracker.go
> +	}
cc @wilfred-s I vote for removing this and don't return anything.

2023-06-13 14:27 UTC, pbacsko commented on pkg/scheduler/ugm/queue_tracker.go
> +func (qt *QueueTracker) setMaxResources(resource *resources.Resource, queuePath string) error {
AH ok, I just checked the commits, this PR contains commits from other PRs... Let's fix those first because I ended up reviewing the same code again.

2023-06-14 08:22 UTC, manirajv06 commented
> I added some comments, but in the meantime I realized I was commenting on stuff that was supposed to be introduced by other PRs... anyway let's get back to this when #543 and #529 are in.

Yes, thats the plan.

2023-06-21 05:56 UTC, wilfred-s requested changes
remove returning errors in internal calls: we only want to do parameter checks in the exported functions in the manager. All others assume correct config etc.
We can also not fail setting any config (like max app or resource) even if the usage is higher than the config.

2023-06-21 05:56 UTC, wilfred-s commented on pkg/scheduler/ugm/queue_tracker.go
> +	}
agree remove the check

2023-06-21 05:56 UTC, wilfred-s commented on pkg/scheduler/ugm/manager.go
> +	groupWildCardLimitsConfig map[string]map[string]interface{} // Hold limits settings of group '*'
Simplify this: introduce a struct type that has two entries. Resource and uint64 to store the wildcard settings in. Store that struct in the map. That safes one indirection and the continuous conversion of the limit object's `map[string]string` to a resource.

2023-06-21 05:56 UTC, wilfred-s commented on pkg/scheduler/ugm/queue_tracker.go
> +		}
return here if not passed: wildcard has been checked and no specific quota was set.

2023-06-21 05:56 UTC, wilfred-s commented on pkg/scheduler/ugm/queue_tracker.go
> +	if (int(qt.maxRunningApps) != 0 && !resources.Equals(resources.NewResource(), qt.maxResources)) || wildCardQuotaExceeded {
no casting to int just use the uint64

2023-06-21 05:56 UTC, wilfred-s commented on pkg/scheduler/ugm/queue_tracker.go
> +
is this a new app to add to the list of running applications?
```
existingApp := runningApplications[appId]
```
Only check maxRunningApps within range if `existingApp == false`

2023-06-21 05:56 UTC, wilfred-s commented on pkg/scheduler/ugm/queue_tracker.go
> +		}
use
```
if allowed := qt....; !allowed {
 return allowed
}
```

2023-06-22 05:56 UTC, wilfred-s requested changes

2023-06-22 05:56 UTC, wilfred-s commented on pkg/scheduler/partition_test.go
> +	assertLimits(t, getTestUserGroup(), resources.Multiply(appRes, 0))
Why is this not a `resource.Zero` ?

2023-06-22 05:56 UTC, wilfred-s commented on pkg/scheduler/ugm/queue_tracker.go
> +		zap.Bool("remove QT", removeQT))
Lot of overhead: we know exactly when we need to remove,
Create a single DEBUG log line:
```
log.Log(log.SchedUGM).Debug("Remove queue tracker",
		zap.String("queue path ", queuePath),
		zap.Bool("remove ", removeQT))
```

2023-06-22 05:56 UTC, wilfred-s commented on pkg/scheduler/ugm/queue_tracker.go
> +			removeQT, decreased := qt.childQueueTrackers[immediateChildQueueName].decreaseTrackedResource(childQueuePath, applicationID, usage, removeApp)
Change to == nil and directly return logging the message

2023-06-22 05:56 UTC, wilfred-s commented on pkg/scheduler/ugm/manager.go
> +		log.Log(log.SchedUGM).Debug("Decreasing resource usage for user",
turn if around

2023-06-22 05:56 UTC, wilfred-s commented on pkg/scheduler/ugm/manager.go
> +			log.Log(log.SchedUGM).Debug("Problem in using the wild card limit max resources settings.",
Assume all resources can be parsed: the config must have passed the  validation before we get here

2023-06-22 05:56 UTC, wilfred-s commented on pkg/scheduler/ugm/queue_tracker.go
> +func (qt *QueueTracker) UnlinkQT(queuePath string) bool {
Parent not needed if we use recursive checks.

root.parent.**child**.leaf
 -> slice of [root, parent, child, leaf]
```
manager -> user.rootQT.unlinkChild(path []slice)
root.unlinkChild([parent, child, leaf])
  root -> find parent
parent.unlinkChild([child.leaf])
   parent -> find child
child.unlinkQT([leaf])
if slice.len ==1 leaf can be removed?
  delete(qt.childQueueTrackers, leaf.queueName)
```

2023-06-22 05:56 UTC, wilfred-s commented on pkg/scheduler/ugm/manager.go
> +					ut.setMaxApplications(0, queuePath)
Use one function to set both, propagate that into all objects

2023-06-22 14:01 UTC, pbacsko requested changes
Please rebase and take care of commit history.

2023-06-23 06:26 UTC, wilfred-s requested changes
look at the lock for the manager as discussed offline

2023-06-23 06:26 UTC, wilfred-s commented on pkg/scheduler/ugm/queue_tracker.go
>  func newQueueTracker(queueName string) *QueueTracker {
new signature: newQueueTracker(queuePath, queueName string) *QueueTracker
add the queuePath filed with the full path to the object:
```
qt.queuePath := queuePath + "." + queueName
qt.queueName := queueName
```
the call for the root queue gets an empty path:
```
rootQueue := newQueueTracker("", configs.RootQueue)
```
when we create a new child we use the current path and the childname:
```
qt.childQueueTracker[child] = newQueueTracker(qt.path, childName)
```
Looking up the queue in the wildcard list:
```
wildcardQuota := getUserWildCardLimitsConfig(qt.path)
```

2023-06-23 09:34 UTC, pbacsko commented on pkg/common/constants.go
> +	WildCard  = "*"
Nit: "wildcard" is a single word, so just `Wildcard` (lowecase "c").

2023-06-26 06:31 UTC, wilfred-s approved these changes
LGTM,
flow in `QueueTracker.increaseTrackedResource()` and `QueueTracker.decreaseTrackedResource()` can be simplified but lets do that in a separate jira so we get the base in

2023-06-26 06:37 UTC, manirajv06 commented
> LGTM, flow in `QueueTracker.increaseTrackedResource()` and `QueueTracker.decreaseTrackedResource()` can be simplified but lets do that in a separate jira so we get the base in

Filed https://issues.apache.org/jira/browse/YUNIKORN-1836 for further simplification

2023-06-26 06:50 UTC, closed without merging