[YUNIKORN-2697] Improve usergroup funtion's test coverage
apache/yunikorn-core pull request #901
Opened 2024-06-24 14:54 UTC by SP12893678

### What is this PR for?
Improve usergroup funtion's test coverage
- usergroup.go
- usergroup_test_resolver.go

### What type of PR is it?
* [x] - Test

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2697

2024-06-25 15:27 UTC, SP12893678 commented
PTAL, In `TestIntervalCacheCleanUp` func, I use sleep method to trigger the `run` func `case <-time.After(c.interval):` case
But it will encount the **race detected during execution of test** problem.
I have no idea to solve it.

2024-06-25 16:50 UTC, pbacsko commented
> PTAL, In `TestIntervalCacheCleanUp` func, I use sleep method to trigger the `run` func `case <-time.After(c.interval):` case But it will encount the **race detected during execution of test** problem. I have no idea to solve it.

I will check in more detail.

2024-06-25 20:14 UTC, pbacsko commented
@SP12893678 you cannot access certain variables without locking.

For example line 286:
```
ug = testCache.ugs["unknown"]
```
this should be:
```
ug = testCache.GetUserGroup("unknown")
```

Another example from line 291:
```
	// expire the failed lookup
	ug.resolved -= 2 * negcache
```
this should be protected by the instance lock:
```
	// expire the failed lookup
	testCache.lock.Lock()
	ug.resolved -= 2 * negcache
	testCache.lock.Unlock()
```

You can compare the two call stacks and check what kind of mutexes are involved. In one case, we clearly don't acquire any mutex.

2024-06-25 20:17 UTC, pbacsko requested changes
Avoid direct access to `UserGroupCache.ugs`.

Obtain/release the instance mutex when modifying `UserGroup.resolved`.

2024-06-29 07:40 UTC, SP12893678 commented
> Avoid direct access to `UserGroupCache.ugs`.
> 
> Obtain/release the instance mutex when modifying `UserGroup.resolved`.

Thanks for the suggestion!
When i use `ug = testCache.GetUserGroup("unknown")` instead of `ug = testCache.ugs["unknown"]`
 I found that `ug.resolved -= 2 * negcache` does not work.
So the clear cache condition will not be met to delete ug key

I append a few lock control to solve it.
But it may not a pretty way.

2024-07-02 12:17 UTC, pbacsko requested changes
Almost. I have a few feedbacks.

Use `assert.XXX()` in the new tests instead of `t.Errorf()` or `t.Fatalf()` to simplify code. Existing tests can stay as they are.

2024-07-02 14:28 UTC, SP12893678 commented
> Almost. I have a few feedbacks.
> 
> Use `assert.XXX()` in the new tests instead of `t.Errorf()` or `t.Fatalf()` to simplify code. Existing tests can stay as they are.

Thanks for your reminder.
It looks simply~

2024-07-04 10:37 UTC, pbacsko requested changes
Ok, I did a deeper review of the locking changes.

Quite a few lock/unlock pair can be removed. `ConvertUGI()` and `GetUserGroup()` both return a copy of existing `UserGroup`, so no need to obtain a lock.

Please see my suggested changes
https://github.com/pbacsko/incubator-yunikorn-core/commit/282ab47d9046fd4e4e6e48b0560154e987f030b1

I ran the tests with `-race` multiple times and there were no problems.

2024-07-04 10:37 UTC, pbacsko commented on pkg/common/security/usergroup_test.go
> +	testCache.lock.Lock()
This lock is not needed here. I believe it should be moved right before L#106 when you directly access `testCache.ugs`. `GetUserGroup()` obtains a lock to read the map and returns a **copy** of the `UserGroup` type, not a pointer.

2024-07-04 10:37 UTC, pbacsko commented on pkg/common/security/usergroup_test.go
> +	testCache.lock.Unlock()
This lock can be removed. `GetUserGroup()` returns a copy and internally uses a mutex to access the map.

2024-07-04 10:37 UTC, pbacsko commented on pkg/common/security/usergroup_test.go
> +	testCache.lock.Lock()
This lock/unlock pair can be removed. `GetUserGroup()` returns a copy and internally uses a mutex to access the map.

2024-07-04 10:37 UTC, pbacsko commented on pkg/common/security/usergroup_test.go
> +	testCache.lock.Unlock()
This lock/unlock pair can be removed. `GetUserGroup()` returns a copy and internally uses a mutex to access the map.

2024-07-04 10:37 UTC, pbacsko commented on pkg/common/security/usergroup_test.go
> +	testCache.lock.Unlock()
This lock/unlock pair can be removed. `GetUserGroup()` returns a copy and internally uses a mutex to access the map.

2024-07-04 10:37 UTC, pbacsko commented on pkg/common/security/usergroup_test.go
> +	testCache.lock.Unlock()
This lock/unlock pair can be removed. `GetUserGroup()` returns a copy and internally uses a mutex to access the map.

2024-07-04 10:37 UTC, pbacsko commented on pkg/common/security/usergroup_test.go
> +	testCache.lock.Unlock()
This lock/unlock pair can be removed. `GetUserGroup()` returns a copy and internally uses a mutex to access the map.

2024-07-04 10:37 UTC, pbacsko commented on pkg/common/security/usergroup_test.go
> +	assert.NilError(t, err, "Lookup should not have failed: testuser1 user")
Small improvement, you can check the `failed` flag here:

```
user1Ug, err := testCache.GetUserGroup("testuser1")
assert.NilError(t, err, "Lookup should not have failed: testuser1 user")
assert.Assert(t, !user1Ug.failed, "User 'testuser1' not resolved as a success")
```

2024-07-04 10:37 UTC, pbacsko commented on pkg/common/security/usergroup_test.go
> +	testCache.lock.Unlock()
This block can be removed, see above.

2024-07-04 10:37 UTC, pbacsko commented on pkg/common/security/usergroup_test.go
> +	testCache.lock.Unlock()
Resolve the `UserGroup` object for "testuser1" here:

```
	// expire the successful lookup
	testCache.lock.Lock()
	ug := testCache.ugs["testuser1"]
	ug.resolved -= 2 * poscache
	testCache.lock.Unlock()
```

This way it's cleaner and more obvious what you're modifying.

2024-07-04 10:37 UTC, pbacsko commented on pkg/common/security/usergroup_test.go
> +	testCache.lock.Unlock()
This lock/unlock pair can be removed. `ConvertUGI()` returns a copy and internally uses a mutex to access the map.

2024-07-04 10:37 UTC, pbacsko commented on pkg/common/security/usergroup_test.go
> +	testCache.lock.Unlock()
This lock/unlock pair can be removed. `ConvertUGI()` returns a copy and internally uses a mutex to access the map.

2024-07-04 10:37 UTC, pbacsko commented on pkg/common/security/usergroup_test.go
> +	testCache.lock.Unlock()
This lock/unlock pair can be removed. `ConvertUGI()` returns a copy and internally uses a mutex to access the map.

2024-07-04 10:37 UTC, pbacsko commented on pkg/common/security/usergroup_test.go
> +	time.Sleep(testCache.interval + 1*time.Second)
Nit: just `time.Second` instead of `1*time.Second`.

2024-07-05 16:35 UTC, SP12893678 commented
> Ok, I did a deeper review of the locking changes.
> 
> Quite a few lock/unlock pair can be removed. `ConvertUGI()` and `GetUserGroup()` both return a copy of existing `UserGroup`, so no need to obtain a lock.
> 
> Please see my suggested changes [pbacsko@282ab47](https://github.com/pbacsko/incubator-yunikorn-core/commit/282ab47d9046fd4e4e6e48b0560154e987f030b1)
> 
> I ran the tests with `-race` multiple times and there were no problems.

Thanks for having reviewed it and found some unnecessary mutex lock/unlock code.
I refer your suggestion to fix it.
make test` command also passed.

2024-07-14 22:47 UTC, pbacsko approved these changes
+1

2024-07-14 22:50 UTC, closed without merging