[YUNIKORN-2908] unregister its metrics when a queue is removed
apache/yunikorn-core pull request #987
Opened 2024-10-18 23:25 UTC by hguo25

### What is this PR for?
Delete all metrics so a deleted queue will not continue to report 'guaranteed resource' 'max resource' 

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2908

### How should this be tested?

### Screenshots (if appropriate)

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

2024-10-21 14:07 UTC, pbacsko commented
@hguo25 is this chang ready for review? I can only see two "wip" commits. If it's not ready, please make it draft by clicking on "Convert to Draft".

2024-10-21 14:08 UTC, pbacsko commented
Also, when ready, squash the commits into a single one and change the commit message to "[YUNIKORN-nnn] JIRA title" format. Thanks.

2024-10-21 20:17 UTC, hguo25 commented
@pbacsko yes it's ready. Squashed commits as you asked. Please review, thanks

2024-10-22 12:46 UTC, pbacsko requested changes
There's no coverage for the new functions in the "metrics" package. Please extend the coverage.

2024-10-22 20:59 UTC, craigcondit requested changes
Approach is good, add tests (as Peter indicated).

2024-10-24 01:30 UTC, hguo25 commented
thanks @pbacsko @craigcondit I have added test

2024-10-24 11:35 UTC, pbacsko commented on pkg/metrics/queue_test.go
> +	metrics, _ := prometheus.DefaultGatherer.Gather()
Try this
```
metrics, err := prometheus.DefaultGatherer.Gather()
assert.NilError(t, err)
```

2024-10-24 11:35 UTC, pbacsko requested changes
Address linter error.

Run locally with 'make lint".

2024-10-28 11:48 UTC, pbacsko approved these changes
+1 LGTM (pending e2e)

2024-10-29 01:52 UTC, hguo25 commented
@pbacsko thanks for the review. The e2e failed in gang scheduling, which doesn't seem to be related to my change?

2024-10-29 05:24 UTC, wilfred-s commented
We need a follow up on YUNIKORN-2926 to fix the gang scheduling e2e test. The changes I made there are not enough to fix the whole issue. Logged new jira for that.

2024-10-29 19:54 UTC, craigcondit approved these changes
+1 LGTM.

2024-10-29 19:56 UTC, closed without merging